-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.19.0-integration-engines-5-19-0-2-integration-fix-d1-int64-e5ebd17c4a7f6a855bd0d3594e1c593542db3061.1"]
    minimum_pre_commit_version: '0'
