-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@6.2.0-integration-engines-6-2-0-7-feat-update-many-and-return-f165828e67aa4eee12e3988ecaef03a622c2c96c.2"]
    minimum_pre_commit_version: '0'
