-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.4.0-integration-feat-driver-adapters-in-client.1"]
    minimum_pre_commit_version: '0'
