-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.10.0-integration-musl-not-amd64-only-fail-when-using-official-prisma-engines.1"]
    minimum_pre_commit_version: '0'
