-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.8.0-integration-chore-client-wasm-auto-include-poc.3"]
    minimum_pre_commit_version: '0'
