-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@6.3.0-integration-engines-6-3-0-1-feat-relation-exists-aff8bf73313e0df76046e671a2cb2d31491601a3.1"]
    minimum_pre_commit_version: '0'
