-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.14.0-integration-static-wasm-worker-loader.5"]
    minimum_pre_commit_version: '0'
