-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.11.0-integration-webpack-plugin.2"]
    minimum_pre_commit_version: '0'
