-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@7.4.0-integration-engines-7-3-0-19-feat-minor-fixes-on-qc-parameterization-c32a571f4d5d8fe47265c7a4515fcd51d88c7309.1"]
    minimum_pre_commit_version: '0'
