-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.9.0-integration-engines-5-9-0-1-integration-sql-nested-transactions-3-29c424a601638eb3f7c6e163ab70881c72af54b9.1"]
    minimum_pre_commit_version: '0'
