-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.21.0-integration-engines-5-21-0-4-integration-itx-refactor-26f089d271712b9396e7b7b9a0a1088f1941e83b.1"]
    minimum_pre_commit_version: '0'
