-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.22.0-integration-engines-5-22-0-3-integration-itx-refactor-8a24494c6f5beb8b01ae2fb7617a01640f9152ce.2"]
    minimum_pre_commit_version: '0'
