-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@6.4.0-integration-engines-6-4-0-7-chore-rename-error-kinds-6ade8eb07ce6ee78cd81baad86b254c457300340.2"]
    minimum_pre_commit_version: '0'
