-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.11.0-integration-fix-pg-import-ecosystem-tests.1"]
    minimum_pre_commit_version: '0'
