-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.12.0-integration-engines-5-12-0-9-integration-sql-nested-transactions-3a8bf350548bafdbabbd4a7a6824e64f59ef979f.1"]
    minimum_pre_commit_version: '0'
