-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@3.14.0-integration-handle-fmt-panics.11"]
    minimum_pre_commit_version: '0'
