-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@6.14.0-integration-feat-client-wasm-base64-on-nodejs.6"]
    minimum_pre_commit_version: '0'
