-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.13.0-integration-engines-5-13-0-8-feat-exclude-selection-4dcfb875515e5fb2f92a6d294ae5a27098f97dd7.1"]
    minimum_pre_commit_version: '0'
