-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.8.0-integration-engines-4-8-0-34-feat-dmmf-connected-engine-ee487e70470b452b3350f1e15ce530ac3361cab9.1"]
    minimum_pre_commit_version: '0'
