-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.8.0-integration-engines-4-8-0-30-integration-debian-is-now-rhel-244a31f37b9c296665177aca58dd7d2d1e2b0071.1"]
    minimum_pre_commit_version: '0'
