-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@6.16.0-integration-engines-6-16-0-1-fix-migrations-schema-engine-wasm-2a89d0928d9a8bdfc9582be9c7234e271b0f8e24.1"]
    minimum_pre_commit_version: '0'
