-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@7.1.0-integration-engines-7-1-0-1-fix-broken-links-4f977cbccf35d76bd3516f82bb56758fe51d4e5e.1"]
    minimum_pre_commit_version: '0'
