-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.18.0-integration-engines-5-18-0-3-feat-gh-actions-3d6f612a21393259032d9b8630f4b621b4f3c32f.1"]
    minimum_pre_commit_version: '0'
