-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.20.0-integration-engines-5-20-0-6-integration-fix-planetscale-transactions-0deadde8739779d8360ea8c60d2b49693271abcf.2"]
    minimum_pre_commit_version: '0'
