-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.9.0-integration-react-native.4"]
    minimum_pre_commit_version: '0'
