-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@6.6.0-integration-engines-6-6-0-6-feat-schema-engine-adapter-factory-de712d95f26bccd1a80e51eb8093904db8aa8f70.1"]
    minimum_pre_commit_version: '0'
