-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.4.0-integration-libsql-adapter.5"]
    minimum_pre_commit_version: '0'
