-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@6.8.0-integration-engines-6-8-0-25-push-mkywrssuzzlv-862a731f64150f675a47c6dddbc494a2edea95b7.1"]
    minimum_pre_commit_version: '0'
