-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.21.0-integration-engines-5-21-0-2-integration-itx-refactor-aa413b54d4893760c84635debe7d5ea6e54326cb.2"]
    minimum_pre_commit_version: '0'
