-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@5.8.0-integration-engines-5-7-0-25-dependabot-cargo-openssl-0-10-60-9a053826a18b859f8ab4403a00edeca5623f442b.1"]
    minimum_pre_commit_version: '0'
