-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@4.8.0-integration-engines-4-8-0-46-integration-alpine-builds-50f740ec721d2f08956550f9b3e648e4203fbbd2.1"]
    minimum_pre_commit_version: '0'
