-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@6.10.0-integration-fix-orm-1006-fix-subcommands-like-init.4"]
    minimum_pre_commit_version: '0'
