-   id: prisma
    name: prisma
    description: ''
    entry: prisma
    language: node
    'types': [file]
    args: []
    require_serial: false
    additional_dependencies: ["prisma@6.11.0-integration-upgrade-mcp-sdk.1"]
    minimum_pre_commit_version: '0'
